name: Build & Test
on:
  push:
  pull_request:
  schedule:
    - cron:  '0 7 * * MON'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  build_and_test:
    name: Build & Test
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest] #, macos-latest]
        build: [Release]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Git Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      - name: Install Doxygen Ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt install -y doxygen

      - name: Install Doxygen Macos
        if: matrix.os == 'macos-latest'
        run: brew install doxygen

      - name: Install Doxygen Windows
        if: matrix.os == 'windows-latest'
        uses: nick-fields/retry@v4
        with:
          max_attempts: 3
          timeout_minutes: 10
          retry_on: any
          command: choco install doxygen.install --force
          shell: bash

      - name: Generating CMake project
        working-directory: ./bin
        run: cmake .. -DCMAKE_BUILD_TYPE=${{ matrix.build }} -DBUILD_TESTING=ON

      - name: Build Spider library
        working-directory: ./bin
        run: cmake --build . --target spider2 --config ${{ matrix.build }} -j8

      - name: Build Spider test
        working-directory: ./bin
        run: cmake --build . --target all-spider2-test --config ${{ matrix.build }} -j8

      - name: Running tests
        if: matrix.os != 'windows-latest'
        working-directory: ./bin/bin
        run: ./all-spider2-test

      - name: Running tests
        if: matrix.os == 'windows-latest'
        working-directory: ./bin/bin/${{ matrix.build }}
        run: ./all-spider2-test

  analyse-sonar:
    runs-on: ubuntu-latest
    needs: [build_and_test]
    name: Run Sonar Analysis
    strategy:
      matrix:
        os: [ubuntu-latest]
        build: [Debug]
    env:
      BUILD_WRAPPER_OUT_DIR: bw-output
    steps:
      - name: Git Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Install Doxygen Ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt install -y doxygen gcovr

      - name: Install Build Wrapper
        uses: SonarSource/sonarqube-scan-action/install-build-wrapper@v7

      - name: Generating CMake project
        working-directory: ./bin
        run: cmake .. -DCMAKE_BUILD_TYPE=${{ matrix.build }} -DBUILD_TESTING=ON

      - name: Build Spider library
        run: build-wrapper-linux-x86-64 --out-dir ${{ env.BUILD_WRAPPER_OUT_DIR }} cmake --build bin/ --target spider2 --config ${{ matrix.build }} -j8

      - name: Build Spider test
        working-directory: ./bin
        run: cmake --build . --target all-spider2-test --config ${{ matrix.build }} -j8

      - name: Running tests
        working-directory: ./bin/bin
        run: ./all-spider2-test

      - name: Coverage
        working-directory: ./bin
        # run: gcovr -r .. -s --exclude '/.*/bin/' --sonarqube=sonarqube.xml
        run: gcovr -r .. -s --exclude '/.*/bin/' --sonarqube=sonarqubecleaned.xml

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v7
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
